export const productConstants ={ 


    CREATE_PRODUCT_REQUEST : 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS : 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE : 'CREATE_PRODUCT_FAILURE',
    
    GET_ALL_PRODUCTS_REQUEST : 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS : 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE : 'GET_ALL_PRODUCTS_FAILURE',
    
    GET_PRODUCT_REQUEST : 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS : 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE : 'GET_PRODUCT_FAILURE',
    
    UPDATE_PRODUCT_REQUEST : 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS : 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE : 'UPDATE_PRODUCT_FAILURE',
    
    DELETE_PRODUCT_REQUEST : 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS : 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE : 'DELETE_PRODUCT_FAILURE',
    }

    export const formulaireConstants ={ 


        CREATE_FORMULAIRE_REQUEST : 'CREATE_FORMULAIRE_REQUEST',
        CREATE_FORMULAIRE_SUCCESS : 'CREATE_FORMULAIRE_SUCCESS',
        CREATE_FORMULAIRE_FAILURE : 'CREATE_FORMULAIRE_FAILURE',
        
        GET_ALL_FORMULAIRES_REQUEST : 'GET_ALL_FORMULAIRES_REQUEST',
        GET_ALL_FORMULAIRES_SUCCESS : 'GET_ALL_FORMULAIRES_SUCCESS',
        GET_ALL_FORMULAIRES_FAILURE : 'GET_ALL_FORMULAIRES_FAILURE',
        
        GET_FORMULAIRE_REQUEST : 'GET_FORMULAIRE_REQUEST',
        GET_FORMULAIRE_SUCCESS : 'GET_FORMULAIRE_SUCCESS',
        GET_FORMULAIRE_FAILURE : 'GET_FORMULAIRE_FAILURE',
        
        UPDATE_FORMULAIRE_REQUEST : 'UPDATE_FORMULAIRE_REQUEST',
        UPDATE_FORMULAIRE_SUCCESS : 'UPDATE_FORMULAIRE_SUCCESS',
        UPDATE_FORMULAIRE_FAILURE : 'UPDATE_FORMULAIRE_FAILURE',
        
        DELETE_FORMULAIRE_REQUEST : 'DELETE_FORMULAIRE_REQUEST',
        DELETE_FORMULAIRE_SUCCESS : 'DELETE_FORMULAIRE_SUCCESS',
        DELETE_FORMULAIRE_FAILURE : 'DELETE_FORMULAIRE_FAILURE',
        }

        export const cartConstants = {
            ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
            ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
            ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
            GET_CART_REQUEST: 'GET_CART_REQUEST',
            GET_CART_SUCCESS: 'GET_CART_SUCCESS',
            GET_CART_FAILURE: 'GET_CART_FAILURE',
            UPDATE_CART_REQUEST: 'UPDATE_CART_REQUEST',
            UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
            UPDATE_CART_FAILURE: 'UPDATE_CART_FAILURE',
            DELETE_CART_REQUEST: 'DELETE_CART_REQUEST',
            DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
            DELETE_CART_FAILURE: 'DELETE_CART_FAILURE'

        }

        export const carttwoConstants = {
            ADD_TO_CARTTWO_REQUEST: 'ADD_TO_CARTTWO_REQUEST',
            ADD_TO_CARTTWO_SUCCESS: 'ADD_TO_CARTTWO_SUCCESS',
            ADD_TO_CARTTWO_FAILURE: 'ADD_TO_CARTTWO_FAILURE',
            GET_CARTTWO_REQUEST: 'GET_CARTTWO_REQUEST',
            GET_CARTTWO_SUCCESS: 'GET_CARTTWO_SUCCESS',
            GET_CARTTWO_FAILURE: 'GET_CARTTWO_FAILURE',
            UPDATE_CARTTWO_REQUEST: 'UPDATE_CARTTWO_REQUEST',
            UPDATE_CARTTWO_SUCCESS: 'UPDATE_CARTTWO_SUCCESS',
            UPDATE_CARTTWO_FAILURE: 'UPDATE_CARTTWO_FAILURE',
            REMOVE_ITEM_FROM_CART_REQUEST: 'REMOVE_ITEM_FROM_CART_REQUEST',
            REMOVE_ITEM_FROM_CART_SUCCESS: 'REMOVE_ITEM_FROM_CART_SUCCESS',
            REMOVE_ITEM_FROM_CART_FAILURE: 'REMOVE_ITEM_FROM_CART_FAILURE',
            UPDATE_ITEM_QUANTITY_REQUEST: 'UPDATE_ITEM_QUANTITY_REQUEST',
            UPDATE_ITEM_QUANTITY_SUCCESS: 'UPDATE_ITEM_QUANTITY_SUCCESS',
            UPDATE_ITEM_QUANTITY_FAILURE: 'UPDATE_ITEM_QUANTITY_FAILURE',
            CLEAR_CART: 'CLEAR_CART' ,
            NEW_CART_CREATED: 'NEW_CART_CREATED' ,
            GET_ALL_CARTS_REQUEST: 'GET_ALL_CARTS_REQUEST',
                    GET_ALL_CARTS_SUCCESS: 'GET_ALL_CARTS_SUCCESS',
                    GET_ALL_CARTS_FAILURE: 'GET_ALL_CARTS_FAILURE',
        
        }